server.port=8080
spring.application.name=smart-campus-scheduler
spring.data.mongodb.uri=mongodb://localhost:27017/smart_campus_scheduler
spring.data.mongodb.database=smart_campus_scheduler

# Logging configuration
logging.level.root=INFO
logging.level.org.springframework.data.mongodb=WARN
logging.level.org.mongodb.driver=WARN
